
//AUTOGENERATED FILE: DO NOT EDIT
#include "RussianChickenInspector_MINX.h"
using namespace RussianChickenInspector;
int main(int argc, char ** argv)
{
	RussianChickenInspector_MINX * game = new RussianChickenInspector_MINX();
	game->Run();
	exit(0);
}
