
//AUTOGENERATED FILE: DO NOT EDIT
#include "MINX/Game.h"
#include "MINX/GameTime.h"
#include "MINX/Input/Keyboard.h"
#ifndef RussianChickenInspector_MINX_H_
#define RussianChickenInspector_MINX_H_

using namespace MINX;

namespace RussianChickenInspector
{
	class RussianChickenInspector_MINX : public Game
	{
		public:
			RussianChickenInspector_MINX();
			void Initialize();
			void LoadContent();
			void UnloadContent();
			void Update(GameTime * gameTime);
			void Draw(GameTime * gameTime);
	};
}

#endif
